In [3]:
import pandas as pd
import seaborn

In [8]:
flights = seaborn.load_dataset('flights')
flights.head()

   year month  passengers
0  1949   Jan         112
1  1949   Feb         118
2  1949   Mar         132
3  1949   Apr         129
4  1949   May         121

In [10]:
fl_indexed = flights.set_index(['year', 'month'])
fl_indexed.head()

            passengers
year month
1949 Jan           112
     Feb           118
     Mar           132
     Apr           129
     May           121

In [11]:
fl_indexed.loc[1950]

       passengers
month
Jan           115
Feb           126
Mar           141
Apr           135
May           125
Jun           149
Jul           170
Aug           170
Sep           158
Oct           133
Nov           114
Dec           140

In [13]:
fl_indexed.loc[1950:1952]

            passengers
year month
1950 Jan           115
     Feb           126
     Mar           141
     Apr           135
     May           125
     Jun           149
     Jul           170
     Aug           170
     Sep           158
     Oct           133
     Nov           114
     Dec           140
1951 Jan           145
     Feb           150
     Mar           178
     Apr           163
     May           172
     Jun           178
     Jul           199
     Aug           199
     Sep           184
     Oct           162
     Nov           146
     Dec           166
1952 Jan           171
     Feb           180
     Mar           193
     Apr           181
     May           183
     Jun           218
     Jul           230
     Aug           242
     Sep           209
     Oct           191
     Nov           172
     Dec           194

In [15]:
fl_indexed.loc[1950, 'Mar']

passengers    141
Name: (1950, Mar), dtype: int64

In [17]:
fl_indexed.loc[1950].loc['Mar':'Aug']

       passengers
month
Mar           141
Apr           135
May           125
Jun           149
Jul           170
Aug           170

In [18]:
fl_unstacked = fl_indexed.unstack()

In [19]:
fl_unstacked

      passengers
month        Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
year
1949         112  118  132  129  121  135  148  148  136  119  104  118
1950         115  126  141  135  125  149  170  170  158  133  114  140
1951         145  150  178  163  172  178  199  199  184  162  146  166
1952         171  180  193  181  183  218  230  242  209  191  172  194
1953         196  196  236  235  229  243  264  272  237  211  180  201
1954         204  188  235  227  234  264  302  293  259  229  203  229
1955         242  233  267  269  270  315  364  347  312  274  237  278
1956         284  277  317  313  318  374  413  405  355  306  271  306
1957         315  301  356  348  355  422  465  467  404  347  305  336
1958         340  318  362  348  363  435  491  505  404  359  310  337
1959         360  342  406  396  420  472  548  559  463  407  362  405
1960         417  391  419  461  472  535  622  606  508  461  390  432

In [21]:
fl_unstacked.sum(axis=0)

            month
passengers  Jan      2901
            Feb      2820
            Mar      3242
            Apr      3205
            May      3262
            Jun      3740
            Jul      4216
            Aug      4213
            Sep      3629
            Oct      3199
            Nov      2794
            Dec      3142
dtype: int64

In [22]:
fl_unstacked.sum(axis=1)

year
1949    1520
1950    1676
1951    2042
1952    2364
1953    2700
1954    2867
1955    3408
1956    3939
1957    4421
1958    4572
1959    5140
1960    5714
dtype: int64

In [24]:
fl_unstacked['passengers','total'] = fl_unstacked.sum(axis=1)

In [25]:
fl_unstacked

      passengers
month        Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec total
year
1949         112  118  132  129  121  135  148  148  136  119  104  118  1520
1950         115  126  141  135  125  149  170  170  158  133  114  140  1676
1951         145  150  178  163  172  178  199  199  184  162  146  166  2042
1952         171  180  193  181  183  218  230  242  209  191  172  194  2364
1953         196  196  236  235  229  243  264  272  237  211  180  201  2700
1954         204  188  235  227  234  264  302  293  259  229  203  229  2867
1955         242  233  267  269  270  315  364  347  312  274  237  278  3408
1956         284  277  317  313  318  374  413  405  355  306  271  306  3939
1957         315  301  356  348  355  422  465  467  404  347  305  336  4421
1958         340  318  362  348  363  435  491  505  404  359  310  337  4572
1959         360  342  406  396  420  472  548  559  463  407  362  405  5140
1960         417  391  419  461  472  535  622  606  508  461  390  432  5714

In [26]:
fl_restacked = fl_unstacked.stack()

In [31]:
fl_restacked.loc[1950]

       passengers
month
Jan           115
Feb           126
Mar           141
Apr           135
May           125
Jun           149
Jul           170
Aug           170
Sep           158
Oct           133
Nov           114
Dec           140
total        1676

In [39]:
fl_restacked.loc[pd.IndexSlice[:,'total'],'passengers']

year  month
1949  total    1520
1950  total    1676
1951  total    2042
1952  total    2364
1953  total    2700
1954  total    2867
1955  total    3408
1956  total    3939
1957  total    4421
1958  total    4572
1959  total    5140
1960  total    5714
Name: passengers, dtype: int64

In [48]:
fl_restacked[(fl_restacked['passengers']>500) & (fl_restacked['passengers']<1500)]

            passengers
year month
1958 Aug           505
1959 Jul           548
     Aug           559
1960 Jun           535
     Jul           622
     Aug           606
     Sep           508