In [1]:
import numpy as np
import pandas as pd

In [2]:
pop2014 = pd.Series([100,99.3,95.5,93.5,92.4,84.8,84.5,78.9,74.3,72.8],
                    index=['Java','C','C++','Python','C#','PHP','JavaScript','Ruby','R','Matlab'])

In [3]:
pop2015 = pd.Series({'Java': 100,'C': 99.9,'C++': 99.4,'Python': 96.5,'C#': 91.3,
                     'R': 84.8,'PHP': 84.5,'JavaScript': 83.0,'Ruby': 76.2,'Matlab': 72.4})

In [4]:
ty = pd.DataFrame({'2014':pop2014, '2015':pop2015})

In [5]:
ty

             2014   2015
C            99.3   99.9
C#           92.4   91.3
C++          95.5   99.4
Java        100.0  100.0
JavaScript   84.5   83.0
Matlab       72.8   72.4
PHP          84.8   84.5
Python       93.5   96.5
R            74.3   84.8
Ruby         78.9   76.2

In [9]:
ty.sort_values('2015', ascending=False)

             2014   2015
Java        100.0  100.0
C            99.3   99.9
C++          95.5   99.4
Python       93.5   96.5
C#           92.4   91.3
R            74.3   84.8
PHP          84.8   84.5
JavaScript   84.5   83.0
Ruby         78.9   76.2
Matlab       72.8   72.4

In [10]:
ty.values

array([[ 99.3,  99.9],
       [ 92.4,  91.3],
       [ 95.5,  99.4],
       [100. , 100. ],
       [ 84.5,  83. ],
       [ 72.8,  72.4],
       [ 84.8,  84.5],
       [ 93.5,  96.5],
       [ 74.3,  84.8],
       [ 78.9,  76.2]])

In [11]:
ty.index

Index(['C', 'C#', 'C++', 'Java', 'JavaScript', 'Matlab', 'PHP', 'Python', 'R',
       'Ruby'],
      dtype='object')

In [12]:
ty.columns

Index(['2014', '2015'], dtype='object')

In [14]:
ty['2015']

C              99.9
C#             91.3
C++            99.4
Java          100.0
JavaScript     83.0
Matlab         72.4
PHP            84.5
Python         96.5
R              84.8
Ruby           76.2
Name: 2015, dtype: float64

In [15]:
ty.iloc[0:3]

     2014  2015
C    99.3  99.9
C#   92.4  91.3
C++  95.5  99.4

In [16]:
ty.loc['Java':'R']

             2014   2015
Java        100.0  100.0
JavaScript   84.5   83.0
Matlab       72.8   72.4
PHP          84.8   84.5
Python       93.5   96.5
R            74.3   84.8

In [17]:
ty['avg'] = 0.5 * (ty['2014'] + ty['2015'])

In [18]:
ty

             2014   2015     avg
C            99.3   99.9   99.60
C#           92.4   91.3   91.85
C++          95.5   99.4   97.45
Java        100.0  100.0  100.00
JavaScript   84.5   83.0   83.75
Matlab       72.8   72.4   72.60
PHP          84.8   84.5   84.65
Python       93.5   96.5   95.00
R            74.3   84.8   79.55
Ruby         78.9   76.2   77.55

In [24]:
presidents = pd.DataFrame([
    {'name':'Barack Obama', 'inaguration':2009, 'birthyear':1961},    
    {'name':'George W. Bush', 'inaguration':2001, 'birthyear':1946},
    {'name':'Bill Clinton', 'birthyear':1946, 'inaguration':1993},
    {'name':'George H. W. Bush', 'inaguration':1989, 'birthyear':1924}
])
presidents

                name  inaguration  birthyear
0       Barack Obama         2009       1961
1     George W. Bush         2001       1946
2       Bill Clinton         1993       1946
3  George H. W. Bush         1989       1924

In [25]:
presidents_index = presidents.set_index('name')
presidents_index

                   inaguration  birthyear
name
Barack Obama              2009       1961
George W. Bush            2001       1946
Bill Clinton              1993       1946
George H. W. Bush         1989       1924

In [27]:
presidents_index.loc['Bill Clinton']

inaguration    1993
birthyear      1946
Name: Bill Clinton, dtype: int64

In [29]:
presidents_index.loc['Bill Clinton']['inaguration']

1993

In [31]:
presidents_index['inaguration']['Bill Clinton']

1993

In [32]:
presidents_fathers = pd.DataFrame([
    {'son':'Barack Obama', 'father':'Barack Obama Sr.'},
    {'son':'George W. Bush', 'father':'George H. W. Bush'},
    #{'son':'Bill Clinton', 'father':''},
    {'son':'George H. W. Bush', 'father':'Presccot Bush'}
])
presidents_fathers

                 son             father
0       Barack Obama   Barack Obama Sr.
1     George W. Bush  George H. W. Bush
2  George H. W. Bush      Presccot Bush

In [33]:
pd.merge(presidents, presidents_fathers, left_on='name', right_on='son')

,name,inaguration,birthyear,son,father
0,Barack Obama,2009,1961,Barack Obama,Barack Obama Sr.
1,George W. Bush,2001,1946,George W. Bush,George H. W. Bush
2,George H. W. Bush,1989,1924,George H. W. Bush,Presccot Bush

In [35]:
pd.merge(presidents, presidents_fathers, left_on='name', right_on='son').drop('son', axis=1)

                name  inaguration  birthyear             father
0       Barack Obama         2009       1961   Barack Obama Sr.
1     George W. Bush         2001       1946  George H. W. Bush
2  George H. W. Bush         1989       1924      Presccot Bush

In [40]:
pd.merge(presidents, presidents_fathers, left_on='name', right_on='son', how='outer').drop('son', axis=1)

                name  inaguration  birthyear             father
0       Barack Obama         2009       1961   Barack Obama Sr.
1     George W. Bush         2001       1946  George H. W. Bush
2       Bill Clinton         1993       1946                NaN
3  George H. W. Bush         1989       1924      Presccot Bush